import type { PromptListDefinition } from './prompts';

export const BUILT_IN_PROMPT_LISTS: Record<string, PromptListDefinition> = {
    reflection: {
        id: 'reflection',
        name: 'Daily Reflection',
        sourceType: 'built-in',
        prompts: [
            'What moment from today still feels emotionally charged?',
            'What did I handle well today, even if it was small?',
            'Where did I feel most like myself today?',
            'What felt heavier than it needed to be, and why?',
            'What am I still carrying from today into tomorrow?',
            'What surprised me about my mood, energy, or attention today?',
            'If I re-lived today with one small change, what would it be?',
            'What did today reveal about what I actually need right now?',
        ],
    },
    gratitude: {
        id: 'gratitude',
        name: 'Gratitude and Enoughness',
        sourceType: 'built-in',
        prompts: [
            'What am I grateful for that I would normally overlook?',
            'Who made today easier, warmer, or less lonely?',
            'What part of my life already holds more goodness than I give it credit for?',
            'What simple comfort felt especially meaningful today?',
            'What challenge from today contained something worth appreciating?',
            'What in my environment supported me today?',
            'What memory from today would I like to keep vivid?',
            'What feels quietly enough right now?',
        ],
    },
    planning: {
        id: 'planning',
        name: 'Planning and Focus',
        sourceType: 'built-in',
        prompts: [
            'What is the one thing that would make tomorrow feel successful?',
            'Where am I spreading myself too thin right now?',
            'What deserves focused attention next, and what can wait?',
            'What unfinished loop is stealing mental energy from me?',
            'What support, boundary, or resource would make the next few days easier?',
            'What am I tempted to overcomplicate that could be kept simple?',
            'What would a realistic best-next-step look like?',
            'What should I intentionally stop doing for a few days?',
        ],
    },
    emotional_check_in: {
        id: 'emotional_check_in',
        name: 'Emotional Check-In',
        sourceType: 'built-in',
        prompts: [
            'What emotion has been most present today?',
            'Where do I feel tension or relief in my body right now?',
            'What am I avoiding feeling more directly?',
            'What part of me needs reassurance, space, or honesty?',
            'What triggered me today, and what did that reaction point to?',
            'What helped me regulate, even a little?',
            'If my current mood had a message, what would it say?',
            'What emotional need feels unmet today?',
        ],
    },
    creativity: {
        id: 'creativity',
        name: 'Creativity and Curiosity',
        sourceType: 'built-in',
        prompts: [
            'What idea keeps returning lately, and why might it matter?',
            'What am I curious about enough to explore for 20 minutes?',
            'What would I make if quality and judgment were off the table?',
            'What have I noticed recently that feels rich with possibility?',
            'What problem could I approach more playfully?',
            'What am I hungry to express that I have not given shape to yet?',
            'What constraint could actually improve the work?',
            'What would delight me to make, even if it never became useful?',
        ],
    },
    weekly_review: {
        id: 'weekly_review',
        name: 'Weekly Review',
        sourceType: 'built-in',
        prompts: [
            'What moved forward this week that I do not want to dismiss?',
            'Where did I show consistency this week?',
            'What drained me repeatedly this week?',
            'What felt energizing enough that I want more of it next week?',
            'What lesson kept appearing in different forms this week?',
            'What relationship, habit, or project wants more attention next week?',
            'What should I carry forward, and what should I deliberately leave behind?',
            'What would make next week feel kinder or more grounded?',
        ],
    },
};
